[package]
name = "parallel_downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.20"
webpki-roots = "0.22"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
clap = { version = "3.0", features = ["derive"] }
log = "0.4"
env_logger = "0.9"