[package]
name = "parallel-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
native-tls = "0.2"
url = "2.2"
clap = { version = "4.4", features = ["derive"] }
webpki-roots = "0.26.7"
trust-dns-resolver = "0.23.2"

[dev-dependencies]
cargo-fuzz = "0.12.0"
